modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cfm_wap"
version = "${version}"
displayName = "CFM Refurbished: Watt About Power?"
authors = "Tr3yMix"
description = '''
Introduces a circuit breaker block that powers the electricity network in "MrCrayfish's Furniture Mod: Refurbished" using power from other mods.
'''
logoFile = "assets/neoforge/logo.png"

[[dependencies.cfm_wap]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cfm_wap]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cfm_wap]]
modId = "architectury"
type = "required"
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cfm_wap]]
modId = "framework"
type = "required"
versionRange = "[0.7.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cfm_wap]]
modId = "refurbished_furniture"
type = "required"
versionRange = "[1.0.12,)"
ordering = "AFTER"
side = "BOTH"


[[mixins]]
config = "cfm_wap.mixins.json"
