modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cfm_wap"
version = "${version}"
displayName = "CFM Refurbished: Watt about Power?"
authors = "Tr3yMix"
description = '''
Introduces a circuit breaker block that powers the electricity network in "MrCrayfish's Furniture Mod: Refurbished" using power from other mods.
'''
logoFile = "assets/neoforge/logo.png"

[[dependencies.cfm_wap]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cfm_wap]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cfm_wap]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cfm_wap]]
modId = "framework"
mandatory = true
versionRange = "[0.9.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cfm_wap]]
modId = "refurbished_furniture"
mandatory = true
versionRange = "[1.0.16,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cfm_wap.mixins.json"
